feat: 为生成的 Sitemap 添加 <lastmod>
DuckDuckStudio/yazicbs.github.io pull request #132
Opened 2024-11-24 15:55 UTC by DuckDuckStudio

### 检查清单
- [ ] 有链接Issue吗? -- Resolve  
- [ ] 你检查过没有其他重复的 [拉取请求](https://github.com/DuckDuckStudio/yazicbs.github.io/pulls) 吗?
- [ ] 此拉取请求仅针对一个问题/功能吗?
- [ ] 你验证过你的修改吗?
- [ ] 你确定你的描述足以让开发人员理解你的意图以及解决方案?
- [ ] 你知晓关于网站内容的拉取请求通常不会通过审查

### 修改说明

---

2024-11-24 16:33 UTC, fjwxzde requested changes
每个文件的最后修改时间一致

2024-11-25 03:46 UTC, DuckDuckStudio commented
本地测试正常啊
![image](https://github.com/user-attachments/assets/825414e8-d228-4c61-aa61-061b084db6b8)

2024-11-25 06:41 UTC, Luna-Grace approved these changes

2024-11-25 06:43 UTC, DuckDuckStudio commented
@fjwxzde run test

2024-11-25 06:43 UTC, fjwxzde approved these changes

2024-11-25 06:44 UTC, merged