[TEST] 代码规范性检查
DuckDuckStudio/yazicbs.github.io pull request #36
Opened 2024-08-15 06:33 UTC by DuckDuckStudio

### 检查清单
- [ ] 有链接Issue吗? -- Resolve () 
- [ ] 你检查过没有其他重复的 [拉取请求](https://github.com/DuckDuckStudio/yazicbs.github.io/pulls)吗?
- [ ] 此拉取请求仅针对一个问题/功能吗?
- [ ] 你验证过你的修改吗?
- [ ] 你确定你的描述足以让开发人员理解你的意图以及解决方案?
- [ ] 你知晓关于网站内容的拉取请求通常不会通过审查

### 修改说明

---

2024-08-15 07:47 UTC, DuckDuckStudio commented
阻止合并

2024-08-16 13:37 UTC, Luna-Grace requested changes

2024-08-16 13:37 UTC, Luna-Grace commented on .github/workflows/code-quality.yml
> +      run: |
```suggestion
      run: |
        npm init
```

2024-08-16 13:37 UTC, Luna-Grace commented on .github/workflows/code-quality.yml
> +        npm init stylelint
```suggestion
        npm init stylelint
        npm install --save-dev eslint
        touch .eslintrc.js
```

2024-08-16 13:37 UTC, Luna-Grace commented on .github/workflows/code-quality.yml
> +    #- name: 检查 js 脚本规范
```suggestion
    - name: 检查 js 脚本规范
```

2024-08-16 13:37 UTC, Luna-Grace commented on .github/workflows/code-quality.yml
> +    #  run: npx eslint "**/*.js"
```suggestion
      run: npx eslint "**/*.js"
```

2024-08-16 13:37 UTC, Luna-Grace commented on .github/workflows/code-quality.yml
> +    #  continue-on-error: true
```suggestion
      continue-on-error: true
```

2024-08-16 13:46 UTC, fjwxzde commented
```
ESLint couldn't find an eslint.config.(js|mjs|cjs) file.
```

2024-09-13 10:45 UTC, DuckDuckStudio commented
关闭原因:
1. 合并冲突
2. 网站过大，改起来太耗时
3. 工作流不能稳定执行

2024-09-13 10:45 UTC, closed without merging