feat🚀: 对于手机测试的控制台页面
DuckDuckStudio/yazicbs.github.io pull request #45
Opened 2024-08-30 20:40 UTC by DuckDuckStudio

### 检查清单
- [ ] 有链接Issue吗? -- Resolve  
- [x] 你检查过没有其他重复的 [拉取请求](https://github.com/DuckDuckStudio/yazicbs.github.io/pulls)吗?
- [x] 此拉取请求仅针对一个问题/功能吗?
- [ ] 你验证过你的修改吗?
- [x] 你确定你的描述足以让开发人员理解你的意图以及解决方案?
- [x] 你知晓关于网站内容的拉取请求通常不会通过审查

### 修改说明

添加一个方便在手机上查看控制台输出的网页

> [!WARN]
> 该功能还不稳定请勿合并

---

2024-09-13 13:33 UTC, DuckDuckStudio commented
抱歉，推错分支了

2024-09-18 02:49 UTC, DuckDuckStudio commented
清理工作区

2024-10-02 13:43 UTC, fjwxzde requested changes
![image](https://github.com/user-attachments/assets/9811639b-6314-4dcc-8e0b-a53ba2862bc5)

2024-10-19 09:06 UTC, merged

2024-10-19 10:01 UTC, fjwxzde commented
此拉取请求的修改已被还原