pref: 移动设备优化
DuckDuckStudio/yazicbs.github.io pull request #81
Opened 2024-11-09 15:20 UTC by DuckDuckStudio

允许缩放

### 检查清单
- [x] 有链接Issue吗? -- Resolve #80 
- [x] 你检查过没有其他重复的 [拉取请求](https://github.com/DuckDuckStudio/yazicbs.github.io/pulls) 吗?
- [x] 此拉取请求仅针对一个问题/功能吗?
- [ ] 你验证过你的修改吗?
- [x] 你确定你的描述足以让开发人员理解你的意图以及解决方案?
- [x] 你知晓关于网站内容的拉取请求通常不会通过审查

### 修改说明

Need test in @fjwxzde 's fork repo.

---

2024-11-09 15:53 UTC, fjwxzde commented
For reviews:
- https://fjwxzde.github.io/yazicbs.github.io/Interesting/vacation_countdown/
- https://fjwxzde.github.io/yazicbs.github.io/Interesting/%E9%B8%AD%E5%AD%90%E6%B4%BB%E4%BA%86%E4%BA%BA%E5%87%A0%E5%B2%81/

✅Validation Completed in a Windows 11 x64 PC (Edge)

2024-11-09 15:56 UTC, Luna-Grace requested changes
不能缩小到显示完整内容。

2024-11-09 15:58 UTC, DuckDuckStudio commented
我找找别的方法...

2024-11-10 08:19 UTC, DuckDuckStudio commented
This change will be fixed in other PR.

2024-11-10 08:19 UTC, closed without merging

2024-11-10 09:24 UTC, DuckDuckStudio commented
- #83